spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/monocle
    username: postgres
    password: 123
  flyway:
    enabled: true
    validate-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8082